apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "food-app-router"
  namespace: "foodie"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app: foodie-ingress
spec:
  rules:
    - http:
        paths:
          - path: /product
            backend:
              serviceName: product-service
              servicePort: 30007
          - path: /*
            backend:
              serviceName: user-service
              servicePort: 30005
