apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: foodie
  labels:
    name: product-service
    app: product-micro-service
spec:
  type: NodePort
  selector:
    app: product-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
