apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  labels:
    name: user-service-deployment
    app: user-micro-service
spec:
  selector:
    matchLabels:
      app: user-app
  replicas: 2
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-app
        image: harendra1987/user-service:0.0.1
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4001
        env:
          - name: DB_URL
            value: mongodb://mongo:27017/user-service

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    name: user-service
    app: user-micro-service
spec:
  type: NodePort
  selector:
    app: user-app
  ports:
  - port: 4001
    targetPort: 4001
    nodePort: 30004