apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: foodie
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-db
        image: mongo
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: foodie
spec:
  selector:
    app: user
  ports:
  - port: 27017
    targetPort: 27017
